import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headerMenu = ["posts", "albums", "todos", "users"];

  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Header menus={headerMenu} />
        {children}
      </body>
    </html>
  );
}
